spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebooking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: springuser
    password: TestPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # keep schema under version-control; no silent creation
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        jta:
          UserTransaction: true

server:
  port: 8081
  error:
    whitelabel:
      enabled: false